### ISSUE TITLE
Vulkan compile error on linux

### ISSUE THREAD

**Issue by vic-ju** [Try/MoltenTempest#10]
The `UniqueHandle` class in Vulkan.hpp is not declared, because of the definition
`add_definitions(-DVULKAN_HPP_NO_SMART_HANDLE)`, but will be used later (line 13075).

I fixed it by just adding the definition
`add_definitions(-DVULKAN_HPP_DISABLE_IMPLICIT_RESULT_VALUE_CAST)`
to skip the code. Not sure if that's okay, though.

I'm using the vulkan-headers 1.2.137-1.

**Comment by Try** [comment]
Hi, @vic-ju !

You change in principle is fine, but I prefer for this kind of case just remove includes of vulkan.hpp in favor of *.h, because engine uses only plain "C" api from vulkan without any wrappers.
