### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vic-ju** [Try/MoltenTempest#11]
Engine is throwing SIGSEGV in `copyUpsample` when trying first `memset` on line 16.

**Comment by Try** [comment]
Hi, @vic-ju and thanks for bug-report!

Can you please provide more contextual information, and a stack-trace for this issue?
Unfortunately line is not enough, since usage of  `copyUpsample` depends on a GPU properties.

**Comment by vic-ju** [comment]
I'm using GCC 8.4 on Manjaro Linux and my system is a Dell XPS 9530. The error occurs right on startup. I just searched the web and it seems that there is no viable vulkan implementation for haswell integrated GPU on linux. My bad!

However, my laptop has a discrete GPU (NVIDIA GT750M) but the vulkan api does not recognize
it. Instead it lists my integrated device two times?


Nevertheless here is the GDB backtrace: [Backtrace1.txt](https://github.com/Try/MoltenTempest/files/4532760/Backtrace1.txt)

**Comment by Try** [comment]
fixed in https://github.com/Try/OpenGothic/issues/74
